import streamlit as st
from PIL import Image

st.set_page_config(
    page_title = "Sonic Log Web App - Guide",
    layout='wide'
    )

st.subheader("How to Use the Web Application")
    
img_manual_1 = Image.open("Manual_page-0001.jpg")
img_manual_2 = Image.open("Manual_page-0002.jpg")
img_manual_3 = Image.open("Manual_page-0003.jpg")
img_manual_4 = Image.open("Manual_page-0004.jpg")
img_manual_5 = Image.open("Manual_page-0005.jpg")
img_manual_6 = Image.open("Manual_page-0006.jpg")
img_manual_7 = Image.open("Manual_page-0007.jpg")
img_manual_8 = Image.open("Manual_page-0008.jpg")
img_manual_9 = Image.open("Manual_page-0009.jpg")
img_manual_10 = Image.open("Manual_page-0010.jpg")
img_manual_11 = Image.open("Manual_page-0011.jpg")
img_manual_12 = Image.open("Manual_page-0012.jpg")
img_manual_13 = Image.open("Manual_page-0013.jpg")
img_manual_14 = Image.open("Manual_page-0014.jpg")
img_manual_15 = Image.open("Manual_page-0015.jpg")
img_manual_16 = Image.open("Manual_page-0016.jpg")
img_manual_17 = Image.open("Manual_page-0017.jpg")
img_manual_18 = Image.open("Manual_page-0018.jpg")
img_manual_19 = Image.open("Manual_page-0019.jpg")
img_manual_20 = Image.open("Manual_page-0020.jpg")
img_manual_21 = Image.open("Manual_page-0021.jpg")
img_manual_22 = Image.open("Manual_page-0022.jpg")
img_manual_23 = Image.open("Manual_page-0023.jpg")
img_manual_24 = Image.open("Manual_page-0024.jpg")
img_manual_25 = Image.open("Manual_page-0025.jpg")
img_manual_26 = Image.open("Manual_page-0026.jpg")
img_manual_27 = Image.open("Manual_page-0027.jpg")
img_manual_28 = Image.open("Manual_page-0028.jpg")
img_manual_29 = Image.open("Manual_page-0029.jpg")
img_manual_30 = Image.open("Manual_page-0030.jpg")
img_manual_31 = Image.open("Manual_page-0031.jpg")

st.image(img_manual_1)
st.image(img_manual_2)
st.image(img_manual_3)
st.image(img_manual_4)
st.image(img_manual_5)
st.image(img_manual_6)
st.image(img_manual_7)
st.image(img_manual_8)
st.image(img_manual_9)
st.image(img_manual_10)
st.image(img_manual_11)
st.image(img_manual_12)
st.image(img_manual_13)
st.image(img_manual_14)
st.image(img_manual_15)
st.image(img_manual_16)
st.image(img_manual_17)
st.image(img_manual_18)
st.image(img_manual_19)
st.image(img_manual_20)
st.image(img_manual_21)
st.image(img_manual_22)
st.image(img_manual_23)
st.image(img_manual_24)
st.image(img_manual_25)
st.image(img_manual_26)
st.image(img_manual_27)
st.image(img_manual_28)
st.image(img_manual_29)
st.image(img_manual_30)
st.image(img_manual_31)